parameters:
    cn_identicon:
        shapes: 
            border:
                -
                    name: 'chevron'
                    points: [0,0,0.5,0,1,0.5,0.5,1,0,1,0.5,0.5]
                -
                    name: 'poisson'
                    points: [0.5,0,0.5,0.5,1,0.5,1,1,0.5,1,0.5,0.5,0,0.5]
                -
                    name: 'deltaplane'
                    points: [0,0,1,0,0.5,0.5,1,0.5,0.5,1,0.5,0.5,0,1]
                -
                    name: 'trough'
                    points: [0,0.5,0.5,1,1,0.5,0.5,0,1,0,1,1,0,1]
                -
                    name: 'rayons'
                    points: [0.5,0,1,0,1,1,0.5,1,1,0.75,0.5,0.5,1,0.25]
                -
                    name: 'double_losange'
                    points: [0,0.5,0.5,0,0.5,0.5,1,0,1,0.5,0.5,1,0.5,0.5,0,1]
                -
                    name: 'couronne'
                    points: [0,0,1,0,1,1,0,1,1,0.5,0.5,0.25,0.5,0.75,0,0.5,0.5,0.25]
                -
                    name: 'biohazard'
                    points: [0,0.5,0.5,0.5,0.5,0,1,0,0.5,0.5,1,0.5,0.5,1,0.5,0.5,0,1]
                -
                    points: [0,0,1,0,0.5,0.5,0.5,0,0,0.5,1,0.5,0.5,1,0.5,0.5,0,1]
                -
                    points: [0,0,1,0,0,1,0,0.5,0.5,0.5,0.5,0,0,0.5]
                -
                    points: [0,0,1,0,1,1,0,1,0,0.5,0.25,0.75,0.5,0.5,0.75,0.75,1,0.5,0.75,0.25,0.5,0.5,0.25,0.25,0,0.5]
                -
                    points: [0.5,0,1,1,0,1,0.5,0,0.5,0.5,0.25,0.75,0.75,0.75,0.5,0.5,]
                -
                    points: [0,0,0,1,1,1,1,0,0,0,0.25,0.5,0,1,0.5,0.75,1,1,0.75,0.5,1,0,0.5,0.25,0.25,0.5,0.5,0.75,0.75,0.5,0.5,0.25]
                -
                    points: [0.75,0.5,0.5,0.75,0.25,0.5,0.5,0.25,0.75,0.5,1,0.5,0.5,1,0,0.5,0.5,0,1,0.5]
                -
                    points: [1,0,1,0.5,0,1,0.5,0]
                -
                    points: [0,1,1,1,0.75,0.5,0.5,1,0.25,0.5,0.5,0,0.75,0.5,1,0,0,0,0.25,0.5]
                -
                    points: [0.75,0.5,1,0.5,0.5,1,0,0.5,0.5,0,0.5,0.25,0.25,0.5,0.5,0.75]
                -
                    points: [0,0,1,0,1,0.5,0.75,0.25,0.25,0.75,0,0.5,0,1,1,1]
                -
                    name: 'stairs'
                    points: [0,0,0,1,0.25,1,0.25,0.75,0.5,0.75,0.5,0.5,0.75,0.5,0.75,0.25,1,0.25,1,0]
            center:
                -
                    name: 'rempli'
                    points: [0,0,1,0,1,1,0,1]
                -
                    name: 'diamand'
                    points: [0.5,0,1,0.5,0.5,1,0,0.5]
                -
                    name: 'inversed_diamand'
                    points: [0,0,1,0,1,1,0,1,0,0.5,0.5,1,1,0.5,0.5,0,0,0.5]
                -
                    name: 'croix'
                    points: [0.25,0,0.75,0,0.5,0.5,1,0.25,1,0.75,0.5,0.5,0.75,1,0.25,1,0.5,0.5,0,0.75,0,0.25,0.5,0.5]
                -
                    name: 'morning_star'
                    points: [0,0,0.5,0.25,1,0,0.75,0.5,1,1,0.5,0.75,0,1,0.25,0.5]
                -
                    name: 'little_square'
                    points: [0.33,0.33,0.67,0.33,0.67,0.67,0.33,0.67]
                -
                    name: 'chess_plate'
                    points: [0,0,0.33,0,0.33,0.33,0.66,0.33,0.67,0,1,0,1,0.33,0.67,0.33,0.67,0.67,1,0.67,1,1,0.67,1,0.67,0.67,0.33,0.67,0.33,1,0,1,0,0.67,0.33,0.67,0.33,0.33,0,0.33]
                -
                    points: [0,0,0,1,1,1,1,0,0,0,0.25,0.5,0,1,0.5,0.75,1,1,0.75,0.5,1,0,0.5,0.25,0.25,0.5,0.5,0.75,0.75,0.5,0.5,0.25]
                -
                    points: [0.75,0.5,0.5,0.75,0.25,0.5,0.5,0.25,0.75,0.5,1,0.5,0.5,1,0,0.5,0.5,0,1,0.5]
                -
                    points: [1,0,1,0.5,0,1,0.5,0]
                -
                    points: [0,1,1,1,0.75,0.5,0.5,1,0.25,0.5,0.5,0,0.75,0.5,1,0,0,0,0.25,0.5]
                -
                    points: [0.25,0.5,0,0.5,0.5,0,1,0.5,0.5,1,0.5,0.75,0.75,0.5,0.5,0.25]
                -
                    name: 'stairs'
                    points: [0,0,0,1,0.25,1,0.25,0.75,0.5,0.75,0.5,0.5,0.75,0.5,0.75,0.25,1,0.25,1,0]